/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { RANGE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const INITIALIZE_SETTINGS_DISCRIMINATOR = new Uint8Array([
  71, 239, 156, 98, 109, 81, 123, 78,
]);

export function getInitializeSettingsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_SETTINGS_DISCRIMINATOR,
  );
}

export type InitializeSettingsInstruction<
  TProgram extends string = typeof RANGE_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountSettings extends string | AccountMeta<string> = string,
  TAccountRangeSigner extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountRent extends string | AccountMeta<string> =
    "SysvarRent111111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountSettings extends string
        ? WritableAccount<TAccountSettings>
        : TAccountSettings,
      TAccountRangeSigner extends string
        ? ReadonlyAccount<TAccountRangeSigner>
        : TAccountRangeSigner,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeSettingsInstructionData = {
  discriminator: ReadonlyUint8Array;
  windowSize: bigint;
};

export type InitializeSettingsInstructionDataArgs = {
  windowSize: number | bigint;
};

export function getInitializeSettingsInstructionDataEncoder(): FixedSizeEncoder<InitializeSettingsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["windowSize", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: INITIALIZE_SETTINGS_DISCRIMINATOR }),
  );
}

export function getInitializeSettingsInstructionDataDecoder(): FixedSizeDecoder<InitializeSettingsInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["windowSize", getU64Decoder()],
  ]);
}

export function getInitializeSettingsInstructionDataCodec(): FixedSizeCodec<
  InitializeSettingsInstructionDataArgs,
  InitializeSettingsInstructionData
> {
  return combineCodec(
    getInitializeSettingsInstructionDataEncoder(),
    getInitializeSettingsInstructionDataDecoder(),
  );
}

export type InitializeSettingsAsyncInput<
  TAccountSigner extends string = string,
  TAccountSettings extends string = string,
  TAccountRangeSigner extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountRent extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  settings?: Address<TAccountSettings>;
  rangeSigner: Address<TAccountRangeSigner>;
  systemProgram?: Address<TAccountSystemProgram>;
  rent?: Address<TAccountRent>;
  windowSize: InitializeSettingsInstructionDataArgs["windowSize"];
};

export async function getInitializeSettingsInstructionAsync<
  TAccountSigner extends string,
  TAccountSettings extends string,
  TAccountRangeSigner extends string,
  TAccountSystemProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof RANGE_PROGRAM_ADDRESS,
>(
  input: InitializeSettingsAsyncInput<
    TAccountSigner,
    TAccountSettings,
    TAccountRangeSigner,
    TAccountSystemProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitializeSettingsInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountSettings,
    TAccountRangeSigner,
    TAccountSystemProgram,
    TAccountRent
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? RANGE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    settings: { value: input.settings ?? null, isWritable: true },
    rangeSigner: { value: input.rangeSigner ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.settings.value) {
    accounts.settings.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([83, 101, 116, 116, 105, 110, 103, 115]),
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.settings),
      getAccountMeta(accounts.rangeSigner),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.rent),
    ],
    data: getInitializeSettingsInstructionDataEncoder().encode(
      args as InitializeSettingsInstructionDataArgs,
    ),
    programAddress,
  } as InitializeSettingsInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountSettings,
    TAccountRangeSigner,
    TAccountSystemProgram,
    TAccountRent
  >);
}

export type InitializeSettingsInput<
  TAccountSigner extends string = string,
  TAccountSettings extends string = string,
  TAccountRangeSigner extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountRent extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  settings: Address<TAccountSettings>;
  rangeSigner: Address<TAccountRangeSigner>;
  systemProgram?: Address<TAccountSystemProgram>;
  rent?: Address<TAccountRent>;
  windowSize: InitializeSettingsInstructionDataArgs["windowSize"];
};

export function getInitializeSettingsInstruction<
  TAccountSigner extends string,
  TAccountSettings extends string,
  TAccountRangeSigner extends string,
  TAccountSystemProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof RANGE_PROGRAM_ADDRESS,
>(
  input: InitializeSettingsInput<
    TAccountSigner,
    TAccountSettings,
    TAccountRangeSigner,
    TAccountSystemProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress },
): InitializeSettingsInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountSettings,
  TAccountRangeSigner,
  TAccountSystemProgram,
  TAccountRent
> {
  // Program address.
  const programAddress = config?.programAddress ?? RANGE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    settings: { value: input.settings ?? null, isWritable: true },
    rangeSigner: { value: input.rangeSigner ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.settings),
      getAccountMeta(accounts.rangeSigner),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.rent),
    ],
    data: getInitializeSettingsInstructionDataEncoder().encode(
      args as InitializeSettingsInstructionDataArgs,
    ),
    programAddress,
  } as InitializeSettingsInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountSettings,
    TAccountRangeSigner,
    TAccountSystemProgram,
    TAccountRent
  >);
}

export type ParsedInitializeSettingsInstruction<
  TProgram extends string = typeof RANGE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    signer: TAccountMetas[0];
    settings: TAccountMetas[1];
    rangeSigner: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
    rent: TAccountMetas[4];
  };
  data: InitializeSettingsInstructionData;
};

export function parseInitializeSettingsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitializeSettingsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      settings: getNextAccount(),
      rangeSigner: getNextAccount(),
      systemProgram: getNextAccount(),
      rent: getNextAccount(),
    },
    data: getInitializeSettingsInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
