/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableSignerAccount,
} from "@solana/kit";
import { RANGE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const VERIFY_RANGE_DISCRIMINATOR = new Uint8Array([
  159, 192, 246, 141, 187, 215, 224, 196,
]);

export function getVerifyRangeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    VERIFY_RANGE_DISCRIMINATOR,
  );
}

export type VerifyRangeInstruction<
  TProgram extends string = typeof RANGE_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountSettings extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountRent extends string | AccountMeta<string> =
    "SysvarRent111111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountSettings extends string
        ? ReadonlyAccount<TAccountSettings>
        : TAccountSettings,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      ...TRemainingAccounts,
    ]
  >;

export type VerifyRangeInstructionData = {
  discriminator: ReadonlyUint8Array;
  signature: ReadonlyUint8Array;
  message: ReadonlyUint8Array;
};

export type VerifyRangeInstructionDataArgs = {
  signature: ReadonlyUint8Array;
  message: ReadonlyUint8Array;
};

export function getVerifyRangeInstructionDataEncoder(): Encoder<VerifyRangeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["signature", addEncoderSizePrefix(getBytesEncoder(), getU32Encoder())],
      ["message", addEncoderSizePrefix(getBytesEncoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: VERIFY_RANGE_DISCRIMINATOR }),
  );
}

export function getVerifyRangeInstructionDataDecoder(): Decoder<VerifyRangeInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["signature", addDecoderSizePrefix(getBytesDecoder(), getU32Decoder())],
    ["message", addDecoderSizePrefix(getBytesDecoder(), getU32Decoder())],
  ]);
}

export function getVerifyRangeInstructionDataCodec(): Codec<
  VerifyRangeInstructionDataArgs,
  VerifyRangeInstructionData
> {
  return combineCodec(
    getVerifyRangeInstructionDataEncoder(),
    getVerifyRangeInstructionDataDecoder(),
  );
}

export type VerifyRangeAsyncInput<
  TAccountSigner extends string = string,
  TAccountSettings extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountRent extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  settings?: Address<TAccountSettings>;
  systemProgram?: Address<TAccountSystemProgram>;
  rent?: Address<TAccountRent>;
  signature: VerifyRangeInstructionDataArgs["signature"];
  message: VerifyRangeInstructionDataArgs["message"];
};

export async function getVerifyRangeInstructionAsync<
  TAccountSigner extends string,
  TAccountSettings extends string,
  TAccountSystemProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof RANGE_PROGRAM_ADDRESS,
>(
  input: VerifyRangeAsyncInput<
    TAccountSigner,
    TAccountSettings,
    TAccountSystemProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  VerifyRangeInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountSettings,
    TAccountSystemProgram,
    TAccountRent
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? RANGE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    settings: { value: input.settings ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.settings.value) {
    accounts.settings.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([83, 101, 116, 116, 105, 110, 103, 115]),
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.settings),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.rent),
    ],
    data: getVerifyRangeInstructionDataEncoder().encode(
      args as VerifyRangeInstructionDataArgs,
    ),
    programAddress,
  } as VerifyRangeInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountSettings,
    TAccountSystemProgram,
    TAccountRent
  >);
}

export type VerifyRangeInput<
  TAccountSigner extends string = string,
  TAccountSettings extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountRent extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  settings: Address<TAccountSettings>;
  systemProgram?: Address<TAccountSystemProgram>;
  rent?: Address<TAccountRent>;
  signature: VerifyRangeInstructionDataArgs["signature"];
  message: VerifyRangeInstructionDataArgs["message"];
};

export function getVerifyRangeInstruction<
  TAccountSigner extends string,
  TAccountSettings extends string,
  TAccountSystemProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof RANGE_PROGRAM_ADDRESS,
>(
  input: VerifyRangeInput<
    TAccountSigner,
    TAccountSettings,
    TAccountSystemProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress },
): VerifyRangeInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountSettings,
  TAccountSystemProgram,
  TAccountRent
> {
  // Program address.
  const programAddress = config?.programAddress ?? RANGE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    settings: { value: input.settings ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.settings),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.rent),
    ],
    data: getVerifyRangeInstructionDataEncoder().encode(
      args as VerifyRangeInstructionDataArgs,
    ),
    programAddress,
  } as VerifyRangeInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountSettings,
    TAccountSystemProgram,
    TAccountRent
  >);
}

export type ParsedVerifyRangeInstruction<
  TProgram extends string = typeof RANGE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    signer: TAccountMetas[0];
    settings: TAccountMetas[1];
    systemProgram: TAccountMetas[2];
    rent: TAccountMetas[3];
  };
  data: VerifyRangeInstructionData;
};

export function parseVerifyRangeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedVerifyRangeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      settings: getNextAccount(),
      systemProgram: getNextAccount(),
      rent: getNextAccount(),
    },
    data: getVerifyRangeInstructionDataDecoder().decode(instruction.data),
  };
}
