/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { RANGE_PROGRAM_ADDRESS } from "../programs";

/** CustomError: Custom error message */
export const RANGE_ERROR__CUSTOM_ERROR = 0x1770; // 6000
/** TimestampParsingFailed: Timestamp Parsing Failed */
export const RANGE_ERROR__TIMESTAMP_PARSING_FAILED = 0x1771; // 6001
/** PubkeyParsingFailed: Pubkey Parsing Failed */
export const RANGE_ERROR__PUBKEY_PARSING_FAILED = 0x1772; // 6002
/** WrongMessageSplitLength: Wrong Message Split Length */
export const RANGE_ERROR__WRONG_MESSAGE_SPLIT_LENGTH = 0x1773; // 6003
/** WrongSigner: Wrong Signer */
export const RANGE_ERROR__WRONG_SIGNER = 0x1774; // 6004
/** CouldntVerifySignature: Couldnt Verify Signature */
export const RANGE_ERROR__COULDNT_VERIFY_SIGNATURE = 0x1775; // 6005
/** TimestampOutOfWindow: Timestamp Out Of Window */
export const RANGE_ERROR__TIMESTAMP_OUT_OF_WINDOW = 0x1776; // 6006

export type RangeError =
  | typeof RANGE_ERROR__COULDNT_VERIFY_SIGNATURE
  | typeof RANGE_ERROR__CUSTOM_ERROR
  | typeof RANGE_ERROR__PUBKEY_PARSING_FAILED
  | typeof RANGE_ERROR__TIMESTAMP_OUT_OF_WINDOW
  | typeof RANGE_ERROR__TIMESTAMP_PARSING_FAILED
  | typeof RANGE_ERROR__WRONG_MESSAGE_SPLIT_LENGTH
  | typeof RANGE_ERROR__WRONG_SIGNER;

let rangeErrorMessages: Record<RangeError, string> | undefined;
if (process.env.NODE_ENV !== "production") {
  rangeErrorMessages = {
    [RANGE_ERROR__COULDNT_VERIFY_SIGNATURE]: `Couldnt Verify Signature`,
    [RANGE_ERROR__CUSTOM_ERROR]: `Custom error message`,
    [RANGE_ERROR__PUBKEY_PARSING_FAILED]: `Pubkey Parsing Failed`,
    [RANGE_ERROR__TIMESTAMP_OUT_OF_WINDOW]: `Timestamp Out Of Window`,
    [RANGE_ERROR__TIMESTAMP_PARSING_FAILED]: `Timestamp Parsing Failed`,
    [RANGE_ERROR__WRONG_MESSAGE_SPLIT_LENGTH]: `Wrong Message Split Length`,
    [RANGE_ERROR__WRONG_SIGNER]: `Wrong Signer`,
  };
}

export function getRangeErrorMessage(code: RangeError): string {
  if (process.env.NODE_ENV !== "production") {
    return (rangeErrorMessages as Record<RangeError, string>)[code];
  }

  return "Error message not available in production bundles.";
}

export function isRangeError<TProgramErrorCode extends RangeError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    RANGE_PROGRAM_ADDRESS,
    code,
  );
}
