//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#initialize_settings;
  pub(crate) mod r#verify_range;

  pub use self::r#initialize_settings::*;
  pub use self::r#verify_range::*;

