/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  type ParsedInitializeSettingsInstruction,
  type ParsedVerifyRangeInstruction,
} from "../instructions";

export const RANGE_PROGRAM_ADDRESS =
  "qU4JaorHz5P8XkB256mKastX4eS3dAkiYVwEo9P1cJ7" as Address<"qU4JaorHz5P8XkB256mKastX4eS3dAkiYVwEo9P1cJ7">;

export enum RangeAccount {
  Settings,
}

export function identifyRangeAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): RangeAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([223, 179, 163, 190, 177, 224, 67, 173]),
      ),
      0,
    )
  ) {
    return RangeAccount.Settings;
  }
  throw new Error(
    "The provided account could not be identified as a range account.",
  );
}

export enum RangeInstruction {
  InitializeSettings,
  VerifyRange,
}

export function identifyRangeInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): RangeInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([71, 239, 156, 98, 109, 81, 123, 78]),
      ),
      0,
    )
  ) {
    return RangeInstruction.InitializeSettings;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([159, 192, 246, 141, 187, 215, 224, 196]),
      ),
      0,
    )
  ) {
    return RangeInstruction.VerifyRange;
  }
  throw new Error(
    "The provided instruction could not be identified as a range instruction.",
  );
}

export type ParsedRangeInstruction<
  TProgram extends string = "qU4JaorHz5P8XkB256mKastX4eS3dAkiYVwEo9P1cJ7",
> =
  | ({
      instructionType: RangeInstruction.InitializeSettings;
    } & ParsedInitializeSettingsInstruction<TProgram>)
  | ({
      instructionType: RangeInstruction.VerifyRange;
    } & ParsedVerifyRangeInstruction<TProgram>);
