//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum RangeError {
    /// 6000 - Custom error message
    #[error("Custom error message")]
    CustomError = 0x1770,
    /// 6001 - Timestamp Parsing Failed
    #[error("Timestamp Parsing Failed")]
    TimestampParsingFailed = 0x1771,
    /// 6002 - Pubkey Parsing Failed
    #[error("Pubkey Parsing Failed")]
    PubkeyParsingFailed = 0x1772,
    /// 6003 - Wrong Message Split Length
    #[error("Wrong Message Split Length")]
    WrongMessageSplitLength = 0x1773,
    /// 6004 - Wrong Signer
    #[error("Wrong Signer")]
    WrongSigner = 0x1774,
    /// 6005 - Couldnt Verify Signature
    #[error("Couldnt Verify Signature")]
    CouldntVerifySignature = 0x1775,
    /// 6006 - Timestamp Out Of Window
    #[error("Timestamp Out Of Window")]
    TimestampOutOfWindow = 0x1776,
}

impl From<RangeError> for solana_program_error::ProgramError {
    fn from(e: RangeError) -> Self {
        solana_program_error::ProgramError::Custom(e as u32)
    }
}

