//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::{pubkey, Pubkey};


  /// `range` program ID.
  pub const RANGE_ID: Pubkey = pubkey!("qU4JaorHz5P8XkB256mKastX4eS3dAkiYVwEo9P1cJ7");

